### ISSUE TITLE
SR-17-0000397 Create Export Files for Madison Metro Middleware

### ISSUE THREAD

**Issue by JaneSchneider-COM** [City-of-Madison/Development-Team-2#13]
**Export Metro Payments received from US Bank**
When online payments are processed through the Treasurer Middleware application, Metro receives an email of payments but would like to now receive a csv file with the payment information as well. They are planning on importing this into their system instead of keying it in manually.

They are requesting this to be able to import into their Metro Record Management System, improve accuracy of data being transferred, save staff time to focus on other tasks

To accomplish this - We will need to get Chris up to speed on the middleware application and make sure he has the right tools on his machine. Then we can take a look at the actual request, we use to provide a export file before we switched over to SSIS packages, I think we should start there and see the export format. 

We will know we are making progress when we have specifications and a mock test file to import and know this is completed when After a month of the export package in production, the file is exported and the customer has agreed that this is completed

This should be completed by end of October and we should be halfway done with a test import and/or manual import into Metro

Resource wise, try to allocate - Chris - 50% of your time with our team; Kim - please be the main resource for Chris; Jane - be present to meetings and knowledge of what's going on

Next Actionable Steps:
- [x] Meet with Chris, Kim, and Jane to go over the middleware application
- [x] Ensure Chris has the right software to work on this
- [ ] Specifications for export
- - [ ] Mapping for Bus Passes @RikiSjachrani-COM
- [ ] SSIS Package in Dev
- [ ] Test file
- [ ] asdf asf sadfsdfa

**Comment by RikiSjachrani-COM** [comment]
@ChrisBilik-COM welcome, you have all the software you need to work on this project? Please let me know...

**Comment by ChrisBilik-COM** [comment]
I think so!  Im going to start with the Metro Billing part, then Bus Passes.  Do we have a mapping for Bus Passes?

**Comment by JaneSchneider-COM** [comment]
Here is location of old Metro export files: \\fps1\Data1\Trcommon\Metro.
Examples attached.
[bp201411101457.txt](https://github.com/City-of-Madison/Development-Team-2/files/1379909/bp201411101457.txt)
[mb201411101457.txt](https://github.com/City-of-Madison/Development-Team-2/files/1379910/mb201411101457.txt)

**Comment by ChrisBilik-COM** [comment]
Can I put columns headers on the.csv output file?

**Comment by JaneSchneider-COM** [comment]
Not sure if Metro's system can handle column headers or not.
@RikiSjachrani-COM: Do you know if column headers would work in the output files for Metro, i.e., can their system handle that? 

@ChrisBilik-COM: What is your reasoning for adding the column headers? Just clarity or something more?

**Comment by ChrisBilik-COM** [comment]
Exactly just for clarity, if not no biggie

**Comment by JaneSchneider-COM** [comment]
@RikiSjachrani-COM or @KimGrittner-COM:
Don't we need Dani to create a view to the Madison Metro data from ePayment?
Attached are screenshots from Test and Prod (is there a dev? What are the login credentials?) 
![epayment_views_prod](https://user-images.githubusercontent.com/30414577/31512173-9ec7e512-af4f-11e7-915a-3f08ccab5eea.JPG)
![epayment_views_test](https://user-images.githubusercontent.com/30414577/31512174-9ee71022-af4f-11e7-9369-97ef54bd043f.JPG)

**Comment by RikiSjachrani-COM** [comment]
There is not a Dev and I think you are right. @DaniFossum-COM do you have a view for Metro Bus Pass and Invoice payments similar to the ones noted above that bizcash can have access to?

**Comment by JaneSchneider-COM** [comment]
FYI - I updated the SourceTypeDescription and AttachmentName fields in the dev bizcash SourceType table for METEXP to "Metro Export" and Metro.pdf to be similar to the %EXP SourceTypes and different than METCOM.
![sourcetypedev_exps](https://user-images.githubusercontent.com/30414577/31513187-1df39c7a-af53-11e7-89a6-99e94ce23304.JPG)

**Comment by KimGrittner-COM** [comment]
JaneSchneider-COM  When you wonder about an ePayment view what fields are you looking for that don't already exist and get populated on MiscDetail?  There are several exports that do NOT use epayment and I wouldn't assume missing data unless we can identify it.

**Comment by JaneSchneider-COM** [comment]
@KimGrittner-COM: True. I  was thinking we would need more info than what is provided in the COM_MET file, but maybe not. Let's cross bridge when we get to it.

**Comment by ChrisBilik-COM** [comment]
I have a sample file of the MetroBill export located at \\fps1\data1\Common\compt\Dev\exportfiles\Metro.    The original sample looks tab delimited, but this ticket said csv, either way can be done.  Going to start Bus Pass next

**Comment by JaneSchneider-COM** [comment]
Excellent! If SR says CSV, then that's what I'd go with for now.

**Comment by ChrisBilik-COM** [comment]
@KimGrittner-COM:  Hey Kim when you get back, I may need some assistance....I am not sure how to make one package do both exports....Do we need another Source type variable?  ie, one for METEX Bill Pay and one for Bus PAss.  I will try to figure it out, but if you have any insight, please let me know.  Easy enough to make another package, but trying to be efficient  :)

**Comment by ChrisBilik-COM** [comment]
Update, both files are exported to \fps1\data1\Common\compt\Dev\exportfiles\Metro
Email is looking good.  Need to understand the pdf report part next

**Comment by ChrisBilik-COM** [comment]
Do we know if the new SSIS export needs to attach 2 pdf reports?    If so @KimGrittner-COM can you give me a once over on that part of the flow?

**Comment by ChrisBilik-COM** [comment]
Attached are the 2 output files for testing:

[bp20171016151913.txt](https://github.com/City-of-Madison/Development-Team-2/files/1392156/bp20171016151913.txt)
[mb20171016151913.txt](https://github.com/City-of-Madison/Development-Team-2/files/1392157/mb20171016151913.txt)

**Comment by RikiSjachrani-COM** [comment]
Does the buss pass output spec include what they purchased? I'm going to give them a call and see if anything has changed since this has been a while

**Comment by ChrisBilik-COM** [comment]
I do not think we got a bus spec(that sheet was blank) so I just made it the same output as the old samples from 2014

**Comment by RikiSjachrani-COM** [comment]
Yeah, just looking at the old output file, it doesn't appear to include any details

**Comment by RikiSjachrani-COM** [comment]
Everyone, I just spoke with Metro's authorized contact and she doesn't know who originally requested this and she is questioning the benefit of it. Please hold of on any development work until I sort this out with Sharon and Nancy. Thanks!

**Comment by RikiSjachrani-COM** [comment]
I just got some additional direction from Sharon and we are going to continue pursuing this, I'm going to call the Metro Contact that is requesting this

![image](https://user-images.githubusercontent.com/13784495/31725028-f71ff694-b3e8-11e7-94fd-9f9c99688658.png)

**Comment by ChrisBilik-COM** [comment]
Excellent!   If the format of the output files is good, we should be good to go, pending changing variable's for the different environment's and such

**Comment by JaneSchneider-COM** [comment]
![gameoff](https://user-images.githubusercontent.com/30414577/31739007-0c3d8018-b412-11e7-898e-1a311207dffc.jpg)

**Comment by JaneSchneider-COM** [comment]
![way](https://user-images.githubusercontent.com/30414577/31739468-9b758b8a-b413-11e7-8607-03cbe5fd4a8b.png)
