### ISSUE TITLE
SR-17-0000403 - Create SSIS Package for water Customer Account file

### ISSUE THREAD

**Issue by KimGrittner-COM** [City-of-Madison/Development-Team-2#14]
WU - Create SSIS Package for water Customer Account file

We have to manually import the customer account file and it would be nice if it would be a push button thing that Water could do, this would pass the responsibility to Water, Save us time from doing it

To accomplish this - Could we have Water have a screen in TR Web where they could upload the Customer Account File and then run some import SSIS package to the Middleware DB?

We will know we are making progress when we have specifications and a mock test file to import and know this is completed when After a month of the import package in production, the file import is done by the customer and we've taken ourselves out of the picture

This should be completed by end of Dec and we should be halfway done with a test import for Water

Resource wise, try to allocate - Chris - 80% of your time with our team; Kim - please be the main resource for Chris; Jane - be present to meetings and knowledge of what's going on
Next Actionable Steps:

- [x] Meet with Chris, Kim, and Jane to go over the manual import of the file
- [x] Brainstorm how this could work
- [x] Specifications for SSIS
- [x] SSIS Package in Dev Environment
- [x] Test SSIS Package in Dev Environment
- [x] Modify TR Web to Call SSIS Package
- [x] Test TR Web in Dev Environment
- [x] Move SSIS package to Test Environment
- [x] Test SSIS Package in Test Environment
- [x] Move TR Web to Test Environment
- [x] Test TR Web in Test Environment
- [x] Move SSIS package to Production Environment
- [x] Test SSIS Package in Production Environment
- [x] Move TR Web to Production Environment
- [x] Test TR Web in Production Environment

**Comment by ChrisBilik-COM** [comment]
I am ready to begin the next phase/testing of the water account import file.  Currently it checks if a file exists, if it does, checks row count and processes the file if data exists and the moves to archive folder.  If no file or no date, the file just goes to archive folder.  Emails are sent with the appropriate message.   I know there is a TR web part on this project, I am not sure what to do with that part? (They are still working on getting me VS, I just contacted the HD)  Anyway, the ssis is pretty slick and will be able to be used for more file imports going forward.  Below is a screenshot of the flow:
![ssiswater](https://user-images.githubusercontent.com/32718943/32063321-78ca3520-ba3c-11e7-9148-eae38d37af92.jpg)

**Comment by ChrisBilik-COM** [comment]
Here is a screenshot of the new Water admin page.   Fairly simple and easy to use. Does this work? Buttons, messages etc...

![water](https://user-images.githubusercontent.com/32718943/32737651-45345114-c860-11e7-8370-1fc73c43d73f.jpg)

**Comment by KimGrittner-COM** [comment]
Looks good to me.

**Comment by ChrisBilik-COM** [comment]
We need to install the latest MSACCESS and Excel drivers on the production box.  It can be found on the C drive of ERPBIZTALKTEST or at : https://www.microsoft.com/en-us/download/details.aspx?id=13255.  This SSIS job will not work without this as the files are .xlsx.  After that we can go through the steps of moving the  package to TestERPDataExports.  I need to see how things are migrated so I can see how configurations work on our SSIS solution.

**Comment by KimGrittner-COM** [comment]
RikiSjachrani-COM do we need a new SR for the request for the server team to install the Office/Excel software on the production ERP Server?

**Comment by RikiSjachrani-COM** [comment]
I will need to defer to the Net Admins on whether we can install the MS Access and Excel drivers. Please stand by

**Comment by RikiSjachrani-COM** [comment]
@ChrisBilik-COM Is this absolutely required? If the Server Team doesn't allow MS Access and/or Excel Drivers, do you have an idea of alternative solutions? Maybe we could ask the file be a csv or tab delimited?

**Comment by ChrisBilik-COM** [comment]
Yes it is required because it is greater than 65k rows...so yes we would need to re-work to be a flat file of sort, text file would be fine....keep in mind we should consider this driver going forward if we are going to be doing larger imports or exports.  Its basically adding the most current  MS OLEDB driver
![driver](https://user-images.githubusercontent.com/32718943/32806554-829ae70a-c952-11e7-91f0-561aeefa81f7.jpg)

**Comment by ChrisBilik-COM** [comment]
Switching to csv is going to few hours or so...all my checks on record counts were based off sql script editor tasks that can be passed in the excel connections....txt/csv does not work that way.  Also need to set up the script tasks to look for new files types and change the connection managers and retest ssis, then update  and retest TR Web

**Comment by RikiSjachrani-COM** [comment]
@ChrisBilik-COM ok, thanks for the information. Hopefully our Net Admins allow the driver install then...we probably won't hear until next week

**Comment by ChrisBilik-COM** [comment]
If we can confirm a standard file for csv or txt we'll be good to go too.  Just need to be consistent with file type.

**Comment by ChrisBilik-COM** [comment]
.csv version is now working

**Comment by RikiSjachrani-COM** [comment]
@ChrisBilik-COM our net admins said it was OK to install those two drivers on the ERPBIZTALK and ERPBIZTALKTEST servers. Please proceed at your convenience

**Comment by ChrisBilik-COM** [comment]
@RikiSjachrani-COM do I do that?  I cant login to those.  We'll chat tomorrow.

**Comment by ChrisBilik-COM** [comment]
The updated driver has been installed on ERPBIZTALK.

**Comment by RikiSjachrani-COM** [comment]
What's the status of this? I'm going through requests that haven't had much progress lately and wondering what would be the next step to getting this moving again?

**Comment by ChrisBilik-COM** [comment]
Its good to go either txt or excel.  Kim and I are going to set up for test this afternoon.

**Comment by ChrisBilik-COM** [comment]
Added source type WTRACT

**Comment by RikiSjachrani-COM** [comment]
What do you think of this for verbiage:

Please use this screen to update the Water Customer and Account Number data. This data is used when the Treasurer's imports the Bill Consolidator file and acts as a lookup. 

This is an import into Middleware, so the file has very specific requirements.
1. It must be an excel file
2. It must contain all the customer and account numbers, this process does not add or keep the previous records
3. The excel file should have two columns, column A should be "**Customer #**" and B "**Account #**"

To import the file, please follow these steps
1. Hit the Browse button
2. Select the excel file
3. Hit the Upload File Button - there should be some information displayed 
4. Now hit the Run Import button

You should receive an email with the results of the import

**Comment by ChrisBilik-COM** [comment]
works for me....I already got the part in where it wont allow anything other then excel files to upload.  Ill start this part next!

**Comment by JaneSchneider-COM** [comment]
Two minor edit suggestions:
1. Replace "Hit" or "hit" with "Click" or "click".
2. In the file requirements numbered list, change #2 as follows:
       It must contain all the customer and account numbers (i.e., this process neither adds nor keeps previous records).

**Comment by ChrisBilik-COM** [comment]
![wat](https://user-images.githubusercontent.com/32718943/34230695-87f907a0-e59e-11e7-80d2-96082604a1ab.jpg)

**Comment by JaneSchneider-COM** [comment]
Two minor edits: 
1. Add space after "numbers" in #2 of first ordered list.
2. Make Click lowercase in #4 of second ordered list.
![trwebtextedits](https://user-images.githubusercontent.com/30414577/34231283-0990d49e-e5a1-11e7-9c36-a2e90a020209.JPG)

**Comment by ChrisBilik-COM** [comment]
Need to copy the WaterAdmin.aspx and the Default.aspx from the wwwroot\trweb folder.  Also need to copy the ERPLoadWTRSCCT.dtsx file from the ERPDataxports folder.

**Comment by ChrisBilik-COM** [comment]
also need to run 64bit access/excel driver on Server.
