### ISSUE TITLE
SR-17-0000467 BI New Record Type Zoning Portable Sign Permit

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#18]
"Need to add a new sign permit type with a modified workflow for portable signs in the right of way that are now allowed by ordinance.  The ordinance specifies that the portable sign permit shall only be valid for a period of one year and must be renewed on an annual basis so this will also need to function like a landlord renewal process with a recurring annual expiration / renewal.

Keep track of portable signs, utilize Accela's capabilities, integrate with existing sign permits and enforcement processes

To accomplish this - Take a look at the RPEC renewal process and the regular Permit Zoning application, we may want to discuss from there on any questions

We will know we are making progress when we have a mocked up version in dev and can show the customer how it works and know this is completed when record type is in production and customer is using it

This should be completed by March 1 st 2018 and we should be halfway done with we have it in test and ready for the customer to do UAT

Resource wise, try to allocate - enough time to learn Accela configuration, Chris Bilik will be the main developer and Jackie a resource on how to do things in Accela

Next Actionable Steps:
- [x] Review document from Kyle
- [x] Create a specifications document to be used in Accela
- [x] Create in Dev
- [ ] Meet with Kyle to show progress
- [x] Create email for Meghan to be notified

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM 
We need a specs for the App Statuses, the example on the PDF is not clear.
[Statuses.pdf](https://github.com/City-of-Madison/Development-Team-2/files/1708867/Statuses.pdf)

**Comment by RikiSjachrani-COM** [comment]
The statuses on the left, under status description are them
