### ISSUE TITLE
SR-18-0000003 FD Guide sheet changes and routine annual inspection scheduling

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#20]
SR-18-0000003 FD Guide sheet changes and routine annual inspection scheduling

This is a bi-annual process to schedule all the routine inspections for the stations. At the beginning of the year, Jerry often has changes to the existing guide sheets. Since the Guide Sheets are added at the time the inspection is scheduled, these changes need to occur prior to the batch.

 - [x] Wait for updated guidesheets
 - [x] Update Guide sheets
 - [ ] Confirm with Jerry and make appropriate changes
 - [x]  re-assign the platoons with station, there's a sql job for this
 - [ ] Schedule batch job
 - [ ] run script to clear out the calendar, this is something that causes slowness for other inspections
 - [ ] confirm and make appropriate changes

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM  The Guide Sheets are updated in Dev, Test and Production.
