### ISSUE TITLE
SR-18-0000052 AA Plan Renewal 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#22]
AA Plan Renewal - This SR is for the work involved with the AA Plan renewals

 - [x] Meet with Jackie and get oriented with project requirements
 - [x] Figure out how the renewal options work with recent changes - Civil Rights will go with the Copy Record functionality
 - [x] Meet with Norman and present different renewal options

Riki 2/6/2018 - After meeting with Norman, they would like the following changes 
 - [x] Make the following related fields blank 46b, 47b, 48b, and 78 checkboxes
 - [x] Change the "Copy Record" button to be "Renew"
 - [ ] Change last step from "Review" to "Review and Finalize" (Where is this set?) JG
 - [x] Send email template of Prequal Renewals to Norman
 - [x] Create similar notification for AA Plan with the adjusted email
 - [ ] They would like to send the email and set the licenses about to expire ASAP! 
 - [x] When a Copy Record occurs, we need to drop and recreate the WAGS table to have lines for the White Males

**Comment by JacquelineGoltz-COM** [comment]
I have a new batch script CIVILRIGHTSAAPLANABOUTTOEXPIRE in Dev.

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM ok, I think the higher priority is to get the White Males to show up for new Copy Record AA Plans.

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM   I was able to use the example Jane provided to clear the text boxes on 46-48 as well as the question 78 checkboxes in Dev for Public Works.  I will complete CBO and Vendor next.

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM and @PaulOLeary-COM ok, I'm looking into the issue with the empty WAGS table causing an emse error
