### ISSUE TITLE
SR-18-0000103 IT ADS Backload – majority of working completed for back loading select Share Point documents into ADS

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#26]
IT ADS Backload - Bug from the project to switch over to primarily using ADS as the default EDMS instead of Share Point. Now, ACA users who need access to historical documents are not able to see them. This SR will create a .net project to be able to pull data from share point and load them into ads. Items to keep into consideration, we need to be able to select certain documents that haven't been a part of the synch, flag the document in share point, and add a entry into the sync table so it doesn't get picked up

\\Fps1\data1\Information Technology\Applications and Systems\Accela\edmsVB\ADSBackload\Changes\SR-18-0000103 IT ADS Backload – majority of working completed for back loading select Share Point documents into ADS

**Comment by RikiSjachrani-COM** [comment]
@KimGrittner-COM hey, just made this workspace up, I was hoping to code through the code and shoot for running something this week.

**Comment by RikiSjachrani-COM** [comment]
@KimGrittner-COM Check out the following code to update the ADS BDocument row with the Doc_Group and Doc_Department Share Point row.

Let's work on integrating this into the solution tomorrow

[Update BDoument from Share Point.txt](https://github.com/City-of-Madison/Development-Team-2/files/1853859/Update.BDoument.from.Share.Point.txt)

**Comment by KimGrittner-COM** [comment]
I put the logging code into the project.  Works with the classes as well as the form.

**Comment by RikiSjachrani-COM** [comment]
@KimGrittner-COM I have this working in Test and have been able to run it successfully. It takes around 11 seconds per document. I'm hoping you could alter the program to run by the exe and then close. I'm hoping to run it on a scheduled job on my computer or a server...

**Comment by KimGrittner-COM** [comment]
The view also allows you to do whatever subset of documents you choose of course.  If  you run it for 1,000 documents and examine the results (TOP 1000) that might lead to a more accurate number in the production environment.

**Comment by PaulOLeary-COM** [comment]
^^^^^ Right, my next comment was gonna be, once we determine the mechanism for running from the server (scheduled task, etc), our first "live ammo" run should be on a very small set. Possibly even tweak the View to select a set of records that doesn't immediately need this fix.

**Comment by RikiSjachrani-COM** [comment]
@KimGrittner-COM , I have some time set aside tomorrow morning to get this to run through an exe and then I'd like to point to production and run a live test against 10 > 100 > 1000 records to see if we get a better rate. I'd really like to tell John Hausbeck that we are beginning to run these in production

**Comment by KimGrittner-COM** [comment]
Ok, we can compile and run it in the morning then.

**Comment by RikiSjachrani-COM** [comment]
![image](https://user-images.githubusercontent.com/13784495/38372440-74a445fc-38b4-11e8-9ffc-9b56a4c2f788.png)
