### ISSUE TITLE
SR-18-0000133 HE: John Requested updating all the Health letters with the new Letterhead

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#28]
HE:  John Requested updating all the Health letters with the new Letterhead.

To Do
- [x] Getting a envelope from the proper agency
 x [ ] Create a excel file from database reports of all health reports
 - [ ] Go through and confirm whether they have letter heads - \\\Fps1\data1\Information Technology\Applications and Systems\Accela\HealthInspections\Changes\SR-18-0000133 HE updating Health letters with new Letterhead
- [ ] Check the SR for documentation of changes, which should have a minimum of
- [ ] Hit List of objects that have been added, modified or deleted
- [ ] Print off current production report through Accela front end, via print preview. (Best practice) Don't do it directly from Report Software
- [ ] Reference to what was added, specifically lines that were modified or deleted
 
Thoughts for later
 - [ ] Steps to recreate error
 - [ ] What example provides the fixed solution

Questions to ask
 - [ ] Is the current report a Crystal Report?
 - [ ] 
 - [ ] 
 - [ ] 
 - [ ] 

Daily Log

Possible things coming out
 - [ ] Have a reference library of agency evelopes

**Comment by RikiSjachrani-COM** [comment]
1.	AgentPlanHoldLetter 	  13-2017-00113
2.	CitationAffidavitofMailing 	  01/01/2018
3.	ExistingSepticLetter 	  SAN-5693
4.	FailingPOWTSNoticeOrder 	  SAN-313
5.	HealthComplaintLog 	  Any Range
6.	HealthEnvrionmentComplaintReport	  HLTCOD-2018-00061
7.	HEBacti5Safe	  HEATNC-2011-01441
8.	HEBactiMCLLtr	  HEATNC-2011-01668 & TCR
9.	HEBactiRecind	  HEATNC-2011-01525
10.	HEBactiSafeLowNitrate	  HEATNC-2012-04454 & BactiSafeLowNitrate
	  HEATNC-2012-04454 & BactiSafeNoNitrate
11.	HEBactiUnsafeLowNO3ltr	  HEATNC-2011-02237
12.	HEConfirmLowNO3Ltr 	  HEATNC-2011-01452
13.	HEFirstTimeHighNitrates	  HEATNC-2011-02026
14.	HEHoldingTankPumperChange	  PERHLD-2015-05720
15.	HoleClosure	  PERPSS-2018-00058
16.	HTNoticeLetter	  2158
17.	HTNoticeTankPump	  2368  & 1/1/18 
18.	PlanApproval	  13-2011-04188
19.	SanitarianReviewHold	  13-2016-00290
20.	SoilSuitability	  PERPSS-2011-04345
21.	SoilTestIncomplete	  PERPSS-2011-00349
22.	SoilTestProblem	  PERPSS-2016-07886
23.	TAMNotification	  13-2011-01155
24.	TamOrders	  SAN-46358
25.	TamOrderSet	  Just Updated Format
26.	WellUnusedMiscInspNotice	  OLDWEL-2017-00006
27.	WellUnusedOrder	  OLDWEL-2017-00032

**Comment by RikiSjachrani-COM** [comment]
@JaneSchneider-COM I finished 1-42

**Comment by JaneSchneider-COM** [comment]
I have finished 43-85. Some of these just have logo, but not full header, so not sure what to do about these, e.g., TAM 1 & 2 Cards; Reinspection Invoice; POWTS Management Plan. 
Some others do have what looks like a full header, but it is not exactly the same as the one used by Well & Septic, e.g,. Temp Food Application; TAM Report.
