### ISSUE TITLE
Affirmative Action Plan Adhoc reporting 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#33]
Move over our discussion on the Adhoc Reporting work for AA Plans from the Orientation thread over to here. I will create a specific SR for this as well.

**Comment by ANavaGomez-COM** [comment]
@ANavaGomez-COM Great! @ChrisHagen-COM is moving the new record type to test today and will bring over this new report as well. Since @ChrisHagen-COM is busy, @JimSchmitt-COM and @ANavaGomez-COM want to help me with some busy work for the Mayor! Stop over and I'll walk you through want needs to be done

**Comment by ANavaGomez-COM** [comment]
![image](https://user-images.githubusercontent.com/13784495/39836041-c0137384-5397-11e8-9a1d-3da51ca4473a.png)

![image](https://user-images.githubusercontent.com/13784495/39836098-e84dd2f4-5397-11e8-8101-09d64c9868d6.png)

Replace space with underscore
Remove special Characters
Try to shorten to 40 characters
ALT_ID => RECORD_ID

 - [x] vw_AA_HEADCOUNT @ANavaGomez-COM 
 - [ ] vw_AA_Plan_Fields @ChrisHagen-COM 
 - [ ] vw_AA_GOALS @JimSchmitt-COM -> Please try and order the columns in a appropriate fashion, check out the record AAPLAN-2015-00036
 - [x] vw_AA_Exempt_Gen_Info RikiSjachrani-COM

**Comment by ANavaGomez-COM** [comment]
@ANavaGomez-COM I see you put in a comment in the view, excellent! 

"Comments are like dessert, something is better than nothing" - Riki Proverb

![image](https://user-images.githubusercontent.com/13784495/39838205-43089926-539e-11e8-9cab-767437abf1ac.png)

**Comment by ANavaGomez-COM** [comment]
OK, I'm half done w/ the CR_AA_GOALS. . . .  I've created the view, replaced spaces with '_', and switched to uppercase.  The problem is that I'm having trouble locating the AAPLAN-2018-00138, so not able to re-order the field names.  I can pick up where I left off tomorrow.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM 

I pushed the new CR_AA_Plan_Fields view to DEV. Very complex, but I didn't want to be the hold up while renaming the 192 lines that are part of it!

all dates should be in date format using CAST.

**Comment by ANavaGomez-COM** [comment]
@JimSchmitt-COM See if you can search for a record type of Licenses/Civil Rights/AA Plan/Public Works

**Comment by ANavaGomez-COM** [comment]
@ANavaGomez-COM want to stop over and help me start working on this one adhoc report?

**Comment by ANavaGomez-COM** [comment]
Fields are grouped a little better. My changes are in "CR_AA_GOALS_ITJAS". Do you want to look at it, Riki?

**Comment by ANavaGomez-COM** [comment]
Sure, let me take a look

**Comment by ANavaGomez-COM** [comment]
@JimSchmitt-COM looks good! I replaced the one you had so we only have the one. I'm hooking it up to Adhoc report now.

@ChrisHagen-COM I don't see your view yet? Maybe you didn't push 

![image](https://user-images.githubusercontent.com/13784495/39874570-c57ef7de-5433-11e8-8f39-150eb940633e.png)

**Comment by ANavaGomez-COM** [comment]
[ACCELA Utilization Report](\Fps1\data1\Information Technology\Applications and Systems\Accela\Active Projects\AA Plan Support Period\ACCELA Utilization Report.xls)

**Comment by ANavaGomez-COM** [comment]
Have CAST the fields for CR_AA_GOALS....

**Comment by ANavaGomez-COM** [comment]
The CR_AA_GOALS and CR_AA_HEADCOUNT look great in Dev. I'm going to move these and the CR_AA_EXEMPT_GEN_INFO, CR_AA_COLLECTIVE_BARGAINING, and CR_AA_RECORD to Test. Any luck on recreating that report?

**Comment by ANavaGomez-COM** [comment]
Not quite yet. I am using 2 views to try to re-create the report: CR_AA_HEADCOUNT, and CR_AA_RECORD. Are these the correct views?

I applied a filter to CR_AA_RECORD > CONTACT EEOAA OFFICER BUSINESS (col) to display "Company" with a RECORD_STATUS of "Approved" and that gives me "Personal" as the value. Am I using the correct view? Thank you.

**Comment by ANavaGomez-COM** [comment]
Also not sure about filters. I'm using Record_Type_Category to filter out everything but "Public Works", "Vendors and Suppliers" and "CBO", and Status to select "Active". Seems like it will not be possible to get a count for Disability and Female since neither field is numerical, and there doesn't seem to be but one record per company? Am I missing something?

**Comment by ANavaGomez-COM** [comment]
Also there seem to be a couple of bad records where total is less than the sum of the various ethnic categories. I would think that would be a problem. . . . I know that many surveys don't require you to select an ethnic category, so I can see the sum being less than the total, but not the other way round. Maybe I shouldn't get hung up on the structure of test data?

**Comment by ANavaGomez-COM** [comment]
I've recreated AAPLAN-2018-00001 to be similar to Abby Vans, Inc.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM , @JimSchmitt-COM - I added a test report named: italn_test\italn_first_report\italn_first_report - The last fields that shows column "DISABLED" has an expression in it that gives the R/E# aggregated value. Click the gauge to see it. In order to create a field like this one, a field from the view most be selected to be used as a "placeholder", and enter a name ins the description too. If the chosen field needs to be included in the expression, the field needs to be explicitly added. I hope this is clear, let me know.

**Comment by ANavaGomez-COM** [comment]
![image](https://user-images.githubusercontent.com/38921618/39894391-48080e4c-546c-11e8-8f71-ab6684ad2c74.png)

**Comment by ANavaGomez-COM** [comment]
![abbyvansadhoc](https://user-images.githubusercontent.com/38922244/39928723-a63e75dc-5525-11e8-969c-6ae9717f4590.jpg)

**Comment by ANavaGomez-COM** [comment]
Totals?!? D'oh! Will have to look at that....

I've got my version saved as "itjas_utilization_by_company" in adhoc

**Comment by ANavaGomez-COM** [comment]
@ANavaGomez-COM or @JimSchmitt-COM, if you could, could you please update the view "CR_AA_PLAN_FIELDS" and cast the Number fields and also default the nulls and blanks appropriately? Thanks

**Comment by ANavaGomez-COM** [comment]
I can work on it. It looks like some of the values are invalid in some cases. For example "PROMOTIONS_TOTAL_LAST_YEAR" has , numerical values, and text values. I'm guessing that replacing the text values and with 0 would be appropriate? Other fields such as "SUBCON_YES_ARE_SUBCON" contain , "Checked", and "Unchecked". . . . I'm not sure what to do with those.

**Comment by ANavaGomez-COM** [comment]
@JimSchmitt-COM thanks, the checked and unchecked are the valid for checkboxes so let's leave those. the number fields are the main concern if we end up doing any math

**Comment by ANavaGomez-COM** [comment]
For `RECORD_ID IN ('AAPLAN-2018-00001', 'AAPLAN-2018-00002')` the Total values should be 148 and 118. This also causes the percentages to be off. 

These should be the numbers:

![image](https://user-images.githubusercontent.com/38921618/40003383-cd6c999c-5758-11e8-87c9-1bb67eff521f.png)

R/E#:

`SUM([BLACK_NOT_OF_HISPANIC_ORIGIN]+[HISPANIC]+[ASIAN_OR_PACIFIC_ISLANDER]+[AMERICAN_INDIAN_OR_ALASKAN_NATIVE]+[TWO_OR_MORE_RACES]))`

Total#:

`	SUM([DBO].[CR_AA_HEADCOUNT].[BLACK_NOT_OF_HISPANIC_ORIGIN]+ 
		[DBO].[CR_AA_HEADCOUNT].[HISPANIC]+ 
		[DBO].[CR_AA_HEADCOUNT].[ASIAN_OR_PACIFIC_ISLANDER]+ 
		[DBO].[CR_AA_HEADCOUNT].[AMERICAN_INDIAN_OR_ALASKAN_NATIVE]+ 
		[DBO].[CR_AA_HEADCOUNT].[TWO_OR_MORE_RACES])+  
		SUM(CASE 
				WHEN [DBO].[CR_AA_HEADCOUNT].[GENDER] = 'Female' THEN
					[DBO].[CR_AA_HEADCOUNT].[TOTAL]
				ELSE 
					0
			END) +  
		SUM(CASE 
				WHEN [DBO].[CR_AA_HEADCOUNT].[DISABLED] = 'Yes' THEN 
					[DBO].[CR_AA_HEADCOUNT].[TOTAL]
				ELSE 
					0
			END)`

Percent%:
`CONVERT(DECIMAL(5,3), 1.0 * SUM([BLACK_NOT_OF_HISPANIC_ORIGIN]+[HISPANIC]+[ASIAN_OR_PACIFIC_ISLANDER]+[AMERICAN_INDIAN_OR_ALASKAN_NATIVE]+[TWO_OR_MORE_RACES])) / (SUM([BLACK_NOT_OF_HISPANIC_ORIGIN]+[HISPANIC]+[ASIAN_OR_PACIFIC_ISLANDER]+[AMERICAN_INDIAN_OR_ALASKAN_NATIVE]+[TWO_OR_MORE_RACES])+  SUM(CASE WHEN [DBO].[CR_AA_HEADCOUNT].[GENDER] = 'Female' THEN [DBO].[CR_AA_HEADCOUNT].[TOTAL] ELSE 0 END) + SUM(CASE WHEN [DBO].[CR_AA_HEADCOUNT].[DISABLED] = 'Yes' THEN [DBO].[CR_AA_HEADCOUNT].[TOTAL] ELSE 0 END))`

**Comment by ANavaGomez-COM** [comment]
@ANavaGomez-COM-The problem is not in adhoc reporting.  Individual records in Accela Automation have been saved with invalid data:

Company                        RE#         Female#     Disability# Total
------------------------------ ----------- ----------- ----------- -----------
Abby Vans, Inc.                31          0           0           31
Abby Vans, Inc.                7           40          0           40
Abby Vans, Inc.                4           0           23          23
Abby Vans, Inc.                3           0           0           82
Abby Vans, Inc.                0           40          0           40
Accela, Inc.                   7           0           0           76
Accela, Inc.                   5           61          0           61
Accela, Inc.                   45          0           0           45

(8 row(s) affected)

SQL for the above data:

```
SELECT 
		CAST([DBO].[CR_AA_RECORD].[CONTACT_EEOAA_OFFICER_BUSINESS] AS VARCHAR(30)) AS 'Company'
		,[CR_AA_HEADCOUNT].[AMERICAN_INDIAN_OR_ALASKAN_NATIVE] 
			+ [CR_AA_HEADCOUNT].[ASIAN_OR_PACIFIC_ISLANDER] 
			+ [CR_AA_HEADCOUNT].[BLACK_NOT_OF_HISPANIC_ORIGIN] 
			+ [CR_AA_HEADCOUNT].[HISPANIC] 
			+ [CR_AA_HEADCOUNT].[TWO_OR_MORE_RACES] AS 'RE#'
		,IIF([GENDER] = 'Female',[TOTAL],0) AS 'Female#'
		,IIF([DISABLED] = 'Yes',[TOTAL],0) AS 'Disability#'
		,[CR_AA_HEADCOUNT].[TOTAL] AS 'Total'
	FROM 
		[DBO].[CR_AA_RECORD] 
		LEFT OUTER JOIN [DBO].[CR_AA_HEADCOUNT] ON [DBO].[CR_AA_HEADCOUNT].[RECORD_ID]=[DBO].[CR_AA_RECORD].[RECORD_ID] 
	WHERE 
		[DBO].[CR_AA_RECORD].[RECORD_ID] IN ('AAPLAN-2018-00001','AAPLAN-2018-00002') 
```

**Comment by ANavaGomez-COM** [comment]
I'm getting increasingly frustrated w/ GitHub.  My session is locking up so that I can't type anything.  It seems to save at random times, and other times it is refreshing the screen for the longest time (getting the message from windows about terminating a long-running script).  

You guys having any of these issues?  Is there something I'm doing?  Or, do I have something set up wrong?  It seems to be triggered by copying from the clipboard w/ <CTRL><V> and other, similar keyboard shortcuts....

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM Ran the updates and rebooted several times.  The updater indicates that there are missing updates, but the installer doesn't seem to be installing them, so called the helpdesk back.  Showed Johnny what I was doing, and we went through an "updater/reboot" cycle together.  Now he's going to do some more research and call me back.

Latest status is that 
1) Github had me logged in after a reboot w/o having to login again. 2) Avatar still not appearing in IE.  3) IE still at version 11.0.9600.18860 4) GitHub is still displaying the banner which states: "Please note that GitHub no longer supports old versions of Internet Explorer.

We recommend upgrading to the latest Microsoft Edge, Google Chrome, or Firefox."

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM , @JimSchmitt-COM  - Before learning from the documentation mentioned in the previous [comment](https://github.com/City-of-Madison/Development-Team-2/issues/29#issuecomment-389200046), I was trying to follow a similar style as Jim's, with the outside the sub-query, thinking that Accela would automatically add the filter.

i.e.

`SELECT 	
	AVG(B.PERCENT_R_E) 'AVERAGE_R_E' 
FROM
	(
		SELECT
			[DBO].[CR_AA_HEADCOUNT].RECORD_ID
		,	CONVERT(DECIMAL(5,2), SUM([DBO].[CR_AA_HEADCOUNT].[BLACK_NOT_OF_HISPANIC_ORIGIN]+
				[DBO].[CR_AA_HEADCOUNT].[AMERICAN_INDIAN_OR_ALASKAN_NATIVE]+
				[DBO].[CR_AA_HEADCOUNT].[ASIAN_OR_PACIFIC_ISLANDER]+
				[DBO].[CR_AA_HEADCOUNT].[HISPANIC]+
				[DBO].[CR_AA_HEADCOUNT].[TWO_OR_MORE_RACES]))/CONVERT(DECIMAL(5,2), SUM([DBO].[CR_AA_HEADCOUNT].[TOTAL])) AS 'PERCENT_R_E'
		FROM [DBO].[CR_AA_HEADCOUNT]
		GROUP BY [DBO].[CR_AA_HEADCOUNT].RECORD_ID
	) B
WHERE 
	([RECORD_ID] IN ('AAPLAN-2018-00001','AAPLAN-2018-00002'))`

**Comment by ANavaGomez-COM** [comment]
I've updated the field names in "Sewer Meter Permit" and saved my changes in a temporary report "SewerMeterPermit_itjas". I tested the report in SSRS w/ record "ENGSAM-2018-00274" that I created, but I'm not sure how to proceed from there. I know we had update Accela to call our modified SSRS report, but I can't remember how to access that functionality. Is that what I need to do? Should I have modified the report directly w/o saving it w/ the "_itjas" suffix?

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I am done moving all the comments related to the Adhoc report. I was not sure how to move comments from one issue to another issue, so I just copied and pasted. I hope that is alright with you. Is there anything else I should focus now? Thank you.

**Comment by RikiSjachrani-COM** [comment]
@ANavaGomez-COM so let me know if you have more questions on what needs to happen...I'll have you complete the work and shepard it to test.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I am adding CR_AA_PLAN_FIELDS as a new Ad Hoc Data Source for the Utilization Report, but I cannot see the RECORD_ID column so that I can do the JOIN, I can see the RECORD_ID column if I open the view in SSMS. Do you have any idea why this might be happening? Thank you.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I asked @ChrisHagen-COM  about the RECORD_ID not been displayed in Ad Hoc rpt. He showed me how to clear the cache and then we re-check, and the column showed up. Thank you @ChrisHagen-COM.

**Comment by ANavaGomez-COM** [comment]
[Couple of questions - Utilization Report..txt](https://github.com/City-of-Madison/Development-Team-2/files/2036779/Couple.of.questions.-.Utilization.Report.txt)

**Comment by ANavaGomez-COM** [comment]
[ACCELA Utilization Report v1.xlsx](https://github.com/City-of-Madison/Development-Team-2/files/2036787/ACCELA.Utilization.Report.v1.xlsx)

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I moved over all the latest vw_AA_Views and CR_AA_Views from elamdbdev to elamdbtest\AccelaStage <

**Comment by RikiSjachrani-COM** [comment]
Great, now take a look at the vw_AA_views and change the source of the table to the "AccelaRptRepl" database, that's a recent copy of production which should give you better data. Do you have adhoc reports in Test? Please start creating the same reports in Test

**Comment by ANavaGomez-COM** [comment]
Riki, here is a sample query I put together fusing CBO as a record type example, please tell me if it is somehow close to the requirements you gave me:

`SELECT DISTINCT 
	r.RECORD_ID
,	r.RECORD_TYPE
,	pf.RECORD_CATEGORY
,	r.RECORD_TYPE_CATEGORY
,	pf.GENERAL_COMMUNITY_BASED_ORGANIZATION
,	pf.GENERAL_PUBLIC_WORKS
,	pf.GENERAL_VENDOR_AND_SUPPLIER
FROM 
	[dbo].[CR_AA_RECORD] r 
LEFT JOIN dbo.CR_AA_HEADCOUNT hc
	ON r.RECORD_ID = hc.RECORD_ID
INNER JOIN CR_AA_PLAN_FIELDS pf
	ON r.RECORD_ID = pf.RECORD_ID
WHERE 
	(RECORD_TYPE LIKE '%AA Plan Exemption%' OR RECORD_TYPE LIKE '%Community Based Organization')
AND pf.GENERAL_COMMUNITY_BASED_ORGANIZATION = 'CHECKED'`

Thank you.

**Comment by RikiSjachrani-COM** [comment]
@ANavaGomez-COM I think the where is switch around and should be something like this

WHERE (RECORD_TYPE LIKE '%AA Plan Exemption%' AND pf.GENERAL_COMMUNITY_BASED_ORGANIZATION = 'CHECKED') OR RECORD_TYPE LIKE '%Community Based Organization'

**Comment by ANavaGomez-COM** [comment]
That seems to do the work. Thank you!

**Comment by ANavaGomez-COM** [comment]
https://github.com/City-of-Madison/Development-Team-2/issues/33#issuecomment-391862553 - where do you go to access and change the data source of the ad hoc tables?

**Comment by RikiSjachrani-COM** [comment]
I did it for one view, I Altered the vw_AA_HEADCOUNT view and copied it to AccelaRptRepl and then re-pointed CR_AA_HEADCOUNT to look at the AccelaRptRepl database...

You will need to do the same for the other views and tables.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I changed the id qualifiers for the AccelaStage > CR_AA_HEADCOUNT, CR_AA_RECORD, CR_AA_Plan_Fields views to point to AccelaRptRepl. Then I recreated one of the reports in actest, added all the fields, and when I tried to run it, I got this error:

![image](https://user-images.githubusercontent.com/38921618/40566090-b9258c8e-6034-11e8-8e06-c426d378eadb.png)

**Comment by RikiSjachrani-COM** [comment]
Ok, let me see if I can work the security access

**Comment by ANavaGomez-COM** [comment]
Sounds good. Thank you.

**Comment by RikiSjachrani-COM** [comment]
I think I'll need one of the DBAs to give Accela user access to the AccelaRptRepl database.

**Comment by JimSchmitt-COM** [comment]
Can I get access, too?

Thx

**Comment by ANavaGomez-COM** [comment]
That makes sense. Do you think we can continue this work next week? I am about to head out. I did add the other 2 reports, so even though they are not working right now, once we get the db permissions corrected, they should be ready to be tested.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I tried to run this reports in Test but I still get the same message.

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - These are all the records in AccelaRptRepl that do not have a Business Name regarding CBO, PW, and V&S:

`AAEX-2017-00099
AAEX-2017-00146
AAEX-2018-00116
TMP-18-007892
TMP-18-007891
TMP-18-017762
TMP-18-017765`

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I added the new filter to only look at records with an 'Active', and 'About to Expire' status. These reports are ready to be tested. Thank you.

**Comment by ANavaGomez-COM** [comment]
Hi @RikiSjachrani-COM, 

I ran a test deleting the 3 AA Plan Utilization reports from the DCR directory in Ad Hoc Accela Test. Then I ran an export of the 3 utilization reports from Accela Dev, and imported them in Ad Hoc Accela Test. The test ran fine. 

@JimSchmitt-COM, and I created a zip file from the 3 Utilization reports in Accela Test, but we were unable to import them to Production due to our current limited access. 

I am attaching the zip file with the reports from Test to this comment, so that you can take care of the import to Production step. 

I want to point out that in order for the import job to actually put the reports where they are supposed to show, you need to make sure that the directory where they go, already exists. Otherwise the import job might indicate that it ran successfully, but you will not see the report in the report list. @JimSchmitt-COM and I already created the DCR directory in Ad Hoc Accela Prod so you can just create and run the import using the attached zip file, and the reports will show under the DCR folder after the job completes. 

[aa+plan+-+utilization+rpt_exportData.zip](https://github.com/City-of-Madison/Development-Team-2/files/2085841/aa.plan.-.utilization.rpt_exportData.zip)

Please let me know if you have any questions. Thank you.

**Comment by RikiSjachrani-COM** [comment]
I imported it and it succeeded but I don't see the reports in adhoc in production...? Not sure what to try, any ideas?

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - the same happened to me when I imported them to Test from Dev the first time. My problem was that the reports in dev resided in a different directory italn_test, instead that DCR so when I imported them into Test, the folder italn_test did not existed. I just added the DCR directory in Test and then imported them again.

**Comment by ANavaGomez-COM** [comment]
Did you see my last comment on this thread in Github?

Thank you,
Alejandro

**Comment by RikiSjachrani-COM** [comment]
Ok, I created the directory and will try and import again

**Comment by RikiSjachrani-COM** [comment]
I created the directory and it loaded one report, it looks like the reports were imported correctly in the database and I removed the missing ones and tried importing again. Still not showing up...

![image](https://user-images.githubusercontent.com/13784495/41243949-3dab2ee6-6d69-11e8-88c1-2ad685f41e00.png)

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - That is strange, so you uploaded one report and that one worked, then you tried to upload the 2 remaining reports and those did not show up? I did the same from dev to test, first uploaded 1, then deleted it, and then imported the 3 reports at once, and it worked. I am not sure why isn't working from test to prod. Would you like me to create a new export package and see if that helps somehow?

**Comment by ANavaGomez-COM** [comment]
Hi Riki, would you please give it another try? I am attaching a new zip file with the adhoc reports. Thank you.

[AAPlan+Reports_exportData.zip](https://github.com/City-of-Madison/Development-Team-2/files/2091051/AAPlan.Reports_exportData.zip)

**Comment by ANavaGomez-COM** [comment]
I uploaded a new zip file with the reports, would you please give it another try to the import?

Thank you,
Alejandro

**Comment by RikiSjachrani-COM** [comment]
Still only have one...!

**Comment by ANavaGomez-COM** [comment]
That is a bummer. At this point, I do not know what is the problem. Would you like me to add the other 2 reports manually? so that they are available and ready today.

**Comment by RikiSjachrani-COM** [comment]
I'm going to delete them from the database that are missing from the front end and have you manually add them today.

**Comment by ANavaGomez-COM** [comment]
Sound good. Thanks!

**Comment by RikiSjachrani-COM** [comment]
Ok, I removed them from the database, please see if added them manually works

**Comment by ANavaGomez-COM** [comment]
@RikiSjachrani-COM - I added the reports manually and they are available and working.

**Comment by RikiSjachrani-COM** [comment]
Great, I just took a look and will update the customer
