### ISSUE TITLE
SR-18-0000162 Kitchen Hood Suppression Permit

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#34]
Kitchen Hood Suppression Permit - Use Fire Alarm Permit as example. Add the 3 devices or less checkbox.  Update the Workflow, ACA and Auto Assign to Joe.  $125 fee.  Use the same letter as the full plan review but will need an update.

**Comment by JaneSchneider-COM** [comment]
@RikiSjachrani-COM: Some questions:
1. The ASI field "Alter Kitchen Hood Extinguishing System" already shows up in ACA as "Alter (3) or less components that do not impact the manufacturer’s design"
So, adding the 3 devices or less checkbox is already done???
Or do I need to simply update the AA version of the ASI field to have the same text as the ACA field?
And/Or do we need to add another option for altering more than three devices and/or alterations that impact the manufacturer's design, regardless of the number of devices????

2. There is already a $125 fee in the fee schedule: ALTKHES = Replace, Alter Kitchen Hood Suppression
So, I don't need to add a new fee item, correct? 

Do you have time to discuss this SR on the phone? I'm really not clear on what needs to be done.

**Comment by RikiSjachrani-COM** [comment]
I'm here and we can discuss, I know some of it has already been done, it just needs to be finished since Jackie is on vacation and then training for the next two week.

**Comment by JaneSchneider-COM** [comment]
Should I call you now?

**Comment by RikiSjachrani-COM** [comment]
@JaneSchneider-COM did you see the reply from Bill about removing the "Repair" option? let me know if you have a need to go over this or whether we can complete the request.

**Comment by JaneSchneider-COM** [comment]
@RikiSjachrani-COM: Yes, I did see it. I think I understand what needs to be done. I'll make changes just in Dev, and then you can take a quick look before I move to Test.

**Comment by JaneSchneider-COM** [comment]
@RikiSjachrani-COM : I have completed what I understand to be the desired changes in both Dev & Test. If you want to discuss, please let me know.
