### ISSUE TITLE
SR-18-0000200 Fire Special Occupancy License additions

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#37]
Fire Carnival and Fairs License (New Record type)

**Comment by JacquelineGoltz-COM** [comment]
I have updated the SR with specs from Bill.

**Comment by RikiSjachrani-COM** [comment]
Last email I saw from Bill is sounds like this might just be two additional ASI Checkboxes to the existing Special Fire License type...if that's the case, this might be really easy!

**Comment by JacquelineGoltz-COM** [comment]
Add Exhibit and Trade Shows also.

**Comment by JacquelineGoltz-COM** [comment]
Notified Bill Sullivan that the license is ready to test.
