### ISSUE TITLE
SR-18-0000177 Outdoor Fire Feature Permit (New record type)

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#38]
Outdoor Fire Feature Permit (New record type)
•Outdoor Fire Feature ASI Data
•	Occupancy Type (copy other occupancy type check boxes) should be able to select multiple 
occupancy types
•	Location of Fire Feature:  [Text Field]
•	Fire Feature Fuel Type: Wood   LPG/NG  Other: (Specify)       These options would be a check box with a text box associated with the “other “ option

Use Kitchen Hood Suppression or Burn Natural lawn as examples of setup.  

May still need a list of standard comments.
[Outdoor Fire Feature.docx](https://github.com/City-of-Madison/Development-Team-2/files/2146977/Outdoor.Fire.Feature.docx)

**Comment by JacquelineGoltz-COM** [comment]
Per discussion and email from Bill, the Fire feature Types can be dropdown box.

**Comment by RikiSjachrani-COM** [comment]
After speaking with Bill at the last bi-weekly fire meeting, this will be the next SR to work on

**Comment by JacquelineGoltz-COM** [comment]
I have sent an email to Bill Sullivan for answers.  I have begun a Spec document to keep track of them.

[Specs.docx](https://github.com/City-of-Madison/Development-Team-2/files/2442283/Specs.docx)

**Comment by JimSchmitt-COM** [comment]
Thanks, Jacqueline!

**Comment by JacquelineGoltz-COM** [comment]
Email from Bill:
The fee will be a flat $250 for new, $125 for an alteration to an existing one.
I have attached the standard comments, since it was started in word I just modified our letter.  
Yes, Match Fire Protection Work Permit template.
We were thinking of capturing some of the following ASI data to report against at some later date:
Fuel Type: Natural gas; Propane LPG; Wood/Pellet; Other
Location: On ground; On building
[Outdoor Gas Fireplace ACCELA DRAFT Comments.docx](https://github.com/City-of-Madison/Development-Team-2/files/2446372/Outdoor.Gas.Fireplace.ACCELA.DRAFT.Comments.docx)

**Comment by JacquelineGoltz-COM** [comment]
The new record type has been created in Dev.   @JimSchmitt-COM and I will run some records through ACA and run the workflow to verify that emails, standard comments, fees and reports run correctly. I will then have Jim move the changes to Test.

**Comment by JacquelineGoltz-COM** [comment]
Test version looks good.  I have sent an email to Fire staff to test.

**Comment by RikiSjachrani-COM** [comment]
@JimSchmitt-COM and @JacquelineGoltz-COM let me know if you are still trying to figure out the thing with the standard comments not loading correctly. I'm thinking there's an expression builder order issue?

**Comment by JimSchmitt-COM** [comment]
@RikiSjachrani-COM, @JacquelineGoltz-COM,

I'm not aware of any issues.  This SR is out to the customer for testing. . . .   Were you thinking of another SR when you asked about standard comments?

**Comment by JacquelineGoltz-COM** [comment]
New permit has been put into production and they sr is closed.
