### ISSUE TITLE
SR-18-0000201 Fire Exhibits and Trade Show License (New Record type)

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#39]
Fire Exhibits and Trade Show License (New Record type)

**Comment by JacquelineGoltz-COM** [comment]
Updated the SR with specs from Bill.

**Comment by JacquelineGoltz-COM** [comment]
[Carnivals & Exhibit LICENSES.pdf](https://github.com/City-of-Madison/Development-Team-2/files/2673160/Carnivals.Exhibit.LICENSES.pdf)
[20181114160106817.pdf](https://github.com/City-of-Madison/Development-Team-2/files/2673161/20181114160106817.pdf)

**Comment by JacquelineGoltz-COM** [comment]
Closing due to project scope changing.  I will add this to SR-18-0000200.
