### ISSUE TITLE
SR-18-0000203 FD Administrative Hold Fee 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#41]
FD Administrative Hold Fee - "We need to establish a workflow for an Administrative Hold. This would apply to most record types where information was missing at the intake step. The fee is $100 and should have been created already. This would be our last priority as of today."

**Comment by JacquelineGoltz-COM** [comment]
I sent an email to Bill with the list of questions that Jane provided.
1.	For which Fire record types does this SR apply? Or, maybe a better question: which Fire record types are excluded?
There are 25 Fire Permit record types and 7 Fire License types (including KitchenHoodCleaning, which is not yet in Production).
They all have a workflow task of Intake. See below for list of Fire record types.

2.	Nine fire record types (ContractorAnnualReport; Blasting; General Burn; Natural Lawn burn; FireExtinguisherMaint; AmusementBuilding; LPG; Tank Install; Tank Remove; TentCanopyNotice) already have an Intake task status of “Hold”. 
a.	Is “Hold” the same as “Administrative Hold” or different?
b.	If the same, should the ones already with “Hold” be renamed to “Administrative Hold”?

3.	I do not see any fee item in any of the fire record type’s fee schedules for “Administrative Hold”. 
a.	I see a fee item called "Additional Information Required Fee" with the amount of $125 that is in the Fire Sprinkler Permit fee schedule…should this be used?
b.	Or should a new fee item be created called “Administrative Hold Fee” with an amount of $100 separate from the "Additional Information Required Fee"?
c.	What Account Code should be used for this fee?

4.	How is “Administrative Hold” different from “Additional Info Required”?

5.	How is this enhancement supposed to work? 
a.	When Fire staff selects the “Administrative Hold” status in the Intake task, the associated “Administrative Hold” fee is assessed? 
b.	Is this fee also automatically invoiced? 
c.	Should any emails be automatically sent out? If so, to whom, what content, and what subject line?
d.	Should any other actions happen?


Permitting/Fire Record Types
/Alarm/NA
/AltFireSuppression/NA
/AmusementBuilding/NA
/BlastingNotice/NA
/Burn/General Burn
/Burn/Natural Lawn
/ContractorAnnualReport/NA
/ControlledEgress/NA
/CoveredMall/NA
/Elevator/NA
/Elevator/PeriodicTest
/FireCommandCenter/NA
/Fireworks/Display
/Fireworks/Sales
/HighPiledStorage/NA
/KitchenHood/NA
/LPG/NA
/RoutineFireInspection/NA
/SmokeControlPanels/NA
/SmokeHeatVents/NA
/Sprinkler/NA
/Standpipe/NA
/Tank/Install
/Tank/Removal
/TentCanopyNotice/NA

Licenses/Fire Record Types
/Blasting/NA
/FireExtinguisherMaint/NA
/HazardousMaterials/NA
/KitchenHoodCleaning/NA (**new rec type; not yet in Prod)
/SpecialHazards/NA
/SpecialOccupancy/NA
/TentandCanopy/NA

**Comment by JaneSchneider-COM** [comment]
Jerry's answers to my questions:

1.	For which Fire record types does this SR apply? Or, maybe a better question: which Fire record types are excluded?
a.	See list below – all YES should have an Admin Hold and associated fee
b.	All NO should have a Hold status with no fee associated
There are 25 Fire Permit record types and 7 Fire License types (including KitchenHoodCleaning, which is not yet in Production).
They all have a workflow task of Intake. See below for list of Fire record types.

2.	Nine fire record types (ContractorAnnualReport; Blasting; General Burn; Natural Lawn burn; FireExtinguisherMaint; AmusementBuilding; LPG; Tank Install; Tank Remove; TentCanopyNotice) already have an Intake task status of “Hold”. 
a.	Is “Hold” the same as “Administrative Hold” or different?
i.	Hold is different, as there is no associated fee with a Hold
b.	If the same, should the ones already with “Hold” be renamed to “Administrative Hold”?
i.	No, see above

3.	I do not see any fee item in any of the fire record type’s fee schedules for “Administrative Hold”. 
a.	I see a fee item called "Additional Information Required Fee" with the amount of $125 that is in the Fire Sprinkler Permit fee schedule…should this be used?
i.	No, use the item in section b below, this fee should be removed
b.	Or should a new fee item be created called “Administrative Hold Fee” with an amount of $100 separate from the "Additional Information Required Fee"?
i.	This should be the new fee associated with all Administrative Hold statuses
c.	What Account Code should be used for this fee?
i.	The same as the plan review fee bucket as far as I am aware

4.	How is “Administrative Hold” different from “Additional Info Required”?
a.	Administrative Hold means that the work permit submittal is missing a critical piece of information that prevents it from moving out of Intake.  Additional Info Required generally occurs after Plan Review starts and the reviewer finds something missing that they need to complete their review.

5.	How is this enhancement supposed to work? 
a.	When Fire staff selects the “Administrative Hold” status in the Intake task, the associated “Administrative Hold” fee is assessed? 
i.	Correct
b.	Is this fee also automatically invoiced? 
i.	I do not know the answer to that, but I believe so
c.	Should any emails be automatically sent out? If so, to whom, what content, and what subject line?
i.	That is an answer that Ann can give when she is back from vacation next week
d.	Should any other actions happen?


Permitting/Fire Record Types
/Alarm/NA - YES
/AltFireSuppression/NA - YES
/AmusementBuilding/NA - YES
/BlastingNotice/NA - NO
/Burn/General Burn - NO
/Burn/Natural Lawn - NO
/ContractorAnnualReport/NA - NO
/ControlledEgress/NA - YES
/CoveredMall/NA - YES
/Elevator/NA - NO
/Elevator/PeriodicTest - NO
/FireCommandCenter/NA - YES
/Fireworks/Display - NO
/Fireworks/Sales - NO
/HighPiledStorage/NA - YES
/KitchenHood/NA - YES
/LPG/NA - YES
/RoutineFireInspection/NA - NO
/SmokeControlPanels/NA - YES
/SmokeHeatVents/NA - YES
/Sprinkler/NA - YES
/Standpipe/NA - YES
/Tank/Install - YES
/Tank/Removal - YES
/TentCanopyNotice/NA - NO

Licenses/Fire Record Types
/Blasting/NA - NO
/FireExtinguisherMaint/NA - NO
/HazardousMaterials/NA - NO
/KitchenHoodCleaning/NA (**new rec type; not yet in Prod) - NO
/SpecialHazards/NA - NO
/SpecialOccupancy/NA - NO
/TentandCanopy/NA - NO

**Comment by JaneSchneider-COM** [comment]
Should the "Administrative Hold Fee" be added to all 15 different fee schedules or to just one of the existing fee schedules. Or should a new Fire permit fee schedule be created for common fees like this one?
I  ask, because I noticed that the "Additional Information Required Fee" (FIRSTCH) is only in the FIRSPRNK fee schedule, but has been added to several other Fire permits, like ControlledEgress, AltFireSuppression, Alarm, FireCommandCenter, KitchenHood, SmokeControlPanels, Standpipe.

**Comment by JaneSchneider-COM** [comment]
@RikiSjachrani-COM: It looks like the REINSP fee is in 27 different Fire record type fee schedules, 19 of them with a $100 fee and four each at $75 and $50.  
So, I see three choices regarding the "Administrative Hold Fee"...which would you prefer?
     1. Add to fee schedule of each of the applicable Fire record types (15 total).
     2. Add to existing fee schedule of one record type, but allow to be used by the other fire record types.
     3.  Create a new fee schedule called FIRCMN (or something similar) for fees that are used by multiple Fire record types.

Thanks,
Jane

 

Also, am I reading it correctly in Jerry's answers to my questions that he's saying to remove the "Additional Information Required Fee" of $125 (see his answer to 3a)? Before I disable that fee, should we check with Bill Sullivan?

**Comment by JacquelineGoltz-COM** [comment]
@JaneSchneider-COM  I did QA on a Kitchen Hood Suppression record type and chose Admin Hold on the workflow.  The fee is assessed properly and the email looks correct. Move the changes to test and I will inform the Fire staff.  I also emailed Ann about the Project Name on the emails.  She is out today but we can update the email if needed when she returns.

**Comment by JacquelineGoltz-COM** [comment]
Ann Blackdeer confirmed that the Project Name will be needed on the 10 Permit types and emails.

**Comment by JaneSchneider-COM** [comment]
The Additional Info Required email applied to 10 permit types so far, but the Administrative Hold email applies to 15 rec types.  Because Chris H's Fire email changes are only in Dev so far, I have made the change in Dev only to script CMN:GetFirePermitEmailHdrVals, line 010, to get the Project Name for any Fire Permit.
010 Old: (cmnSubType == "Alarm" || cmnSubType == "Sprinkler") ^  projectName = "Project Name:"+ insertTab + {PROJECT INFORMATION.Project Name};
010 New: {PROJECT INFORMATION.Project Name} != null && {PROJECT INFORMATION.Project Name} != "" ^ projectName = "Project Name:" + insertTab + {PROJECT INFORMATION.Project Name};

Also, this SR has been moved to Test and is ready for Fire to test it.

**Comment by JaneSchneider-COM** [comment]
Please make sure Fire staff knows to use their own email addresses for any Contact on a given Fire permit record when testing in ACA Test, so that emails are sent to them instead of actual businesses.

**Comment by JacquelineGoltz-COM** [comment]
Ann Blackdeer has approved the changes to be moved to production.

**Comment by JaneSchneider-COM** [comment]
I still need to update calls to email helper scripting code now that Chris has moved it to Test. Will do this morning and let you know when done and verified working.

**Comment by JaneSchneider-COM** [comment]
I've completed my updates in Test to use helper scripts from Chris. Made sure Dev & Test are same, and tested a few times to make sure both environments work as expected. Will coordinate with Chris for him to move SR-18-0203 to Prod while I move SR-18-0186 to Prod.

**Comment by JaneSchneider-COM** [comment]
This SR has been moved to production by Chris H and the SR ticket closed.
