### ISSUE TITLE
SR-18-0000213 FD Routine Inspection Checklist 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#45]
FD Routine Inspection Checklist - 
See attached document for original request.
1) Firefighter Devin Rogers – move him up to Prevention level access in Accela
2) Add/change the following violation codes in the Complex guidesheet

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM will you please get together with @JimSchmitt-COM to walk through how to test his changes? I guess just walk through scheduling a new inspection and check the checklist for the changes noted in the SR

Thanks in advance! 

Riki

**Comment by JimSchmitt-COM** [comment]
@JacquelineGoltz-COM do you have some time this morning?

Thanks,

Jim

**Comment by JacquelineGoltz-COM** [comment]
I will come over when I get a chance.  I am on elamsupport today.

**Comment by RikiSjachrani-COM** [comment]
@JacquelineGoltz-COM will you please take over QA of this and notification of the customer?

**Comment by JacquelineGoltz-COM** [comment]
Changes are in production as of 07/30/2018
