### ISSUE TITLE
Elevator Checklist Update - SR-18-0000229

### ISSUE THREAD

**Issue by JacquelineGoltz-COM** [City-of-Madison/Development-Team-2#47]
Update Guidesheet checklists for Elevator.  See  the attached spreadsheet on the SR with changes.

**Comment by JacquelineGoltz-COM** [comment]
Ready for QA.

**Comment by JacquelineGoltz-COM** [comment]
I sent an email to Jerry to inform him this is ready to test.

**Comment by JacquelineGoltz-COM** [comment]
The changes have been promoted to production. I closed the SR.

**Comment by ANavaGomez-COM** [comment]
@JacquelineGoltz-COM  - Thank you!
