### ISSUE TITLE
Map Layers Parcel and Planning Parcels undefined

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#5]
The issue with when identifying or selecting an object from the Parcel or Planning Parcel layers, the Key field 'Parcel', will display as 'Undefined'

[Dev map test](http://elam73dev.cityofmadison.com/agis/?madison)

**Comment by RikiSjachrani-COM** [comment]
Trying to view a parcel and I'm just getting the following 

![image](https://user-images.githubusercontent.com/13784495/28799033-71204c2a-760c-11e7-8215-a6b646c3bd81.png)

**Comment by RikiSjachrani-COM** [comment]
@PaulOLeary-COM so this problem has been resolved right?

**Comment by PaulOLeary-COM** [comment]
@RikiSjachrani-COM Yes, it's resolved.
