### ISSUE TITLE
SR-18-0000293 EN ROW - Engineering would like to add to add a new inspection type and possibly Horizontal Drilling (HDD). 

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#50]
EN ROW - Engineering would like to add to add a new inspection type and possibly Horizontal Drilling (HDD). 
The purpose of this change is to better track this type of work and ensure it's done correctly since they've had a number of issues due to this.

**Comment by RikiSjachrani-COM** [comment]
We are meeting with them on Thursday 11/1

**Comment by ANavaGomez-COM** [comment]
Riki, should I assign myself to this SR in Accela? Thanks

**Comment by RikiSjachrani-COM** [comment]
Sure, I have it assigned to me just because I'm doing to IT Review - Additional Info Needed steps

**Comment by ANavaGomez-COM** [comment]
I am going to leave it as it is right now, since we probably will be meeting with them again soon. Thank you.
