### ISSUE TITLE
SR-18-0000294 Request to add some standard language to ENGROW permits that were issued for horizontal drilling jobs (HDD).

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#51]
Request to add some standard language to ENGROW permits that were issued for horizontal drilling jobs (HDD). 

Currently there are 2 bullet points under that condition and would like to include a 3rd with the following language:

Drilling route shall follow the proposed route shown on the approved plans submitted under this permit application. Any centerline deviation great than 2” shall require the applicant to suspend work until a revised plan has been submitted and approved, or remove the newly installed facility.

Tool: Report Builder
Report name: /Madison/Engineering/PermitToExcavateInPublicROW

**Comment by RikiSjachrani-COM** [comment]
@ANavaGomez-COM would you mind reaching out to someone on the team to quick QA this for you?

**Comment by ANavaGomez-COM** [comment]
I don't mind at all. I will ask someone on the team for sure, right away. Thank you.
