### ISSUE TITLE
SR-17-0000285 Food and Drink AMO Guidesheet Update

### ISSUE THREAD

**Issue by RikiSjachrani-COM** [City-of-Madison/Development-Team-2#6]
HE Updates to the Food and Drink guidesheet and related reports - Health is having to update the terms and language used when they are inspecting and noting Food and Drink inspections. This will mean modifications to their existing checklists and reports.

## Questions
- [x] Reports were using the code in front of the checklist items for grouping, but now the new items do not have them there. Example, ext (Old: "06c - IMPROPER HANDWASHING" vs New: "HANDWASHING - IMPROPER). The 06 meant a violation type of Personal Hygiene.
-  Answer - Had a conference call with Beth and she understands and wants to remove the code in front of the checklist items

# **To Dos**

**Step 0**
- [ ] Figure out a timeline and schedule

**Step 1 - Get these to Test earlier to get sign off before moving on to the next 'Phase'**
- [ ] Create the new guidesheets - include all the pieces for the guidesheets
     - [x]  LIC_FOOD IONN 2017
     - [x]  LIC_FOOD IONN OTHER 2017
     - [x]  LIC FOOD GRP 2017
     - [x]  LIC FOOD GRP OHTHER 2017 

**Step 2**
- [x] Go through the scripts - find all scripts 

**Step 3**
Reports - Coordinate the SSRS migration 
- [x] Health Inspection 
- [x] Health Inspection (AMO)
- [x] Re-inspection report
- [x] Adhoc Violation report  - will need to include the 4 new guide sheets.
- [x] CDC Risk Factor Report 
            * Created a new report that combines the old data and the new data CDC_Report_New
- [x] Online Health Inspection 
- [x] Health Active

Round 1 of Testing by Health (Courtney)
**Overall Fixes Needed:**
- [x] Auto-attach “LIC_FOOD Inspection Details” checklist for the same food inspection types as IONN and GRP auto-attaches to.
- [x] Do not auto-attach “LIC_FOOD GRP Other 2017” or “LIC_FOOD_IONN Other 2017” checklists.  We will manually add these if they are needed.  
- [x] The naming convention for the new checklists only uses an underscore after the word “food” and “IONN” for LIC_FOOD_IONN_2017.  Rename checklist to be “LIC_FOOD IONN 2017” (without the extra underscores) so that it matches the naming style of the other checklists.  
- [x] LIC_FOOD Inspection Details checklist still needs “Cooling Temps” and “Reheating Temps” added.

**LIC_FOOD_IONN_2017 Fixes Needed:**
- [x] Remove the space character from before the title “Handwashing - When”; we need to be able to sort the titles alphabetically, this space throws this one out of order.
- [x] In the violation “Temperature – Cold Holding”, in the Comments text, remove the return/space after “41 degrees F” and the “.” so that the period is not down on the next line and is instead immediately after the F.  We use this violation a LOT and don’t want to have to edit this typo every single time.

**LIC_FOOD GRP OTHER 2017 Fixes Needed:**
- [x] Remove the space character from before the violation title “Linens – Cleaning Frequency”.

**Inspection Report Fixes Needed:**
- [x] Report is not correctly pulling “out” violations and is instead listing ALL violations in alphabetical order and says “No violations at time of inspection” statement on first page.
- [x] Inspections details checklist is not showing up on report.
- [x] Violations that were chosen as “Out” are not displaying compliance date or if corrected on site or repeat violation boxes were checked.
- [x] In summary area of first page, reinspection required says No even though reinspection required was marked yes.

**Comment by RikiSjachrani-COM** [comment]
We should figure out scheduling for this

![image](https://user-images.githubusercontent.com/13784495/28835696-e538b6fc-76ab-11e7-9a40-3cd584723cca.png)

Jackie is out 8/28 thru 9/5 (or 6)

Just go through and decide what is reasonable

Labor day weekend is Taste of Madison so they may not be able to test the week before?

**Comment by BrendenPautsch-COM** [comment]
Added Guidesheet for LIC_FOOD_GRP and vreated the Status group LICFDIO.

Only question, how do we have it default to "null."  Will have to follow up tomorrow with Riki.

**Comment by JacquelineGoltz-COM** [comment]
I added guidesheet for LIC_FOOD_IONN 2017 and added all four status groups LICFDIO, LICFDIONN , LICFDIONA, LICFDIONO.  All are used on this guidesheet type.

**Comment by RikiSjachrani-COM** [comment]
@BrendenPautsch-COM the default for all the guide sheet items should be in, see below screen shot

![image](https://user-images.githubusercontent.com/13784495/28923146-9fc2cb3a-7822-11e7-97ab-fd18a0ac35bb.png)

**Comment by BrendenPautsch-COM** [comment]
I started looking at the reports and noticed that information is missing.  The reports were using the code in front of the Text (Old: "06c - IMPROPER HANDWASHING" vs New: "HANDWASHING - IMPROPER).  

The 06 meant a violation type of Personal Hygiene.  Now there is no way to tell what violation (out of Compliance) category it belongs to.  We may need to contact Beth for more clarification on to categorize each "Out" for the reports.

I will follow up with you on Friday.

**Comment by RikiSjachrani-COM** [comment]
I added a section at the top for questions for Beth, when we have a number of them we should setup a meeting to go over them with her

**Comment by BrendenPautsch-COM** [comment]
Talked with Jackie, we cannot move forward on Reporting until the 1st question is answered.  We think we need that meeting to happen soon rather than waiting for a longer list.

Also I believe that both Jackie and I need to have Accela mobile installed on our workstations since many of the Inspectors do everything local (disconnected)

**Comment by RikiSjachrani-COM** [comment]
ok, I will set up a meeting

**Comment by RikiSjachrani-COM** [comment]
Sorry, didn't mean to close this. Anyways, it looks like Beth is out on vacation all week so I'll ask Sharon how to approach this. You should be able to install the client from https:\\elam.cityofmadison.com\amo and I'll add the instructions I have from them to setup the rest

**Comment by RikiSjachrani-COM** [comment]
[AMO PHMDC User Guide.docx](https://github.com/City-of-Madison/Development-Team-2/files/1205389/AMO.PHMDC.User.Guide.docx)

**Comment by RikiSjachrani-COM** [comment]
I've setup a meeting to go over this with Beth on Tuesday, she is probably going to be super busy Monday. Did you need any assistance in getting the AMO stuff working? We should look at the reports as well and how I've made changes to it

**Comment by JacquelineGoltz-COM** [comment]
I have AMO installed and logged in.  I haven't had a chance to look at anything yet.

**Comment by BrendenPautsch-COM** [comment]
I have installed AMO and I attempted and completed an inspection in test.  The only thing that I was not able to do was run reports.  It kept asking me to install the Crystal add-in

**Comment by BrendenPautsch-COM** [comment]
I am working on the reports, HealthInspection, I was able to modify the 2 dataset for the report to work with bit the new and old guide sheets.  In Dev, the SSRS report HealthInspectionsNew has been updated.  I used the permit LICFDM-2012-00323 and inspection (Pre-inspection  #2327644 & Routine Inspection:  #2406006) for testing data.

**Comment by RikiSjachrani-COM** [comment]
@BrendenPautsch-COM the crystal add in can be installed from the following https://elam.cityofmadison.com/amo/ but it will sometimes initiate when the main exe is installed

**Comment by BrendenPautsch-COM** [comment]
I updated the Stored Procedure that updated Health Active View in DEV to include both the current and new guide sheet violations in its counts so no design changes will be required to any of the reports that use the Health Active Data Source.  I contemplated changing the names to something more logical, but I am not sure how many ad-hoc report Beth and  Courtney have that use the fields [0to27] and [28to55].  Should I make then Name change?  If so there are 2 options.  Keep the old fields and add 2 new fields (same Data) or I can just change the field names, Thoughts?

Everything is looking correct in Dev so far, but I will not be able to test any reports in Test until the Guidesheets are added to Test.

**Comment by RikiSjachrani-COM** [comment]
@BrendenPautsch-COM check out production, I don't see that they've created a report using those fields so I think it might be safe to change it. What do you propose as a better named column? 

Could we move the new checklists to test and let Courtney and Beth know it's ready for them to test?
- [ ] Move checklist items to Test
- [ ] Notify Courtney and Beth

**Comment by JacquelineGoltz-COM** [comment]
I moved the Guidesheet/Checklists to Test.  Brenden could you look them over and make sure everything looks correct?  It does to me.  I will contact Beth and Courtney.

**Comment by BrendenPautsch-COM** [comment]
New Field Names:
- INSPECTION_Violation_Priority   was [INSPECTION_0to27]
- INSPECTION_Violations_Additional was [INSPECTION_28to55]

**Comment by BrendenPautsch-COM** [comment]
I was able to create a new inspection in AMO and I got the new Guidesheets after I did a complete sync.  I believe that it is ready to the tested by Beth and Courtney.

**Comment by JacquelineGoltz-COM** [comment]
Email sent to Courtney and Beth regarding testing

**Comment by BrendenPautsch-COM** [comment]
I moved the SSRS Inspection Report from Dev to Test to test with the new data, attached is the report.  I some how selected an inspection that had carry- forwarded items, bonus.  I will start working on the AMO version of the report.  I want to have a correct version of the report to validate the local AMO report.
[HealthInspectionNew-TEST.pdf](https://github.com/City-of-Madison/Development-Team-2/files/1232602/HealthInspectionNew-TEST.pdf)

**Comment by RikiSjachrani-COM** [comment]
Great to hear! The AMO version of the report is located here C:\Program Files\Accela Inc\Accela Mobile Office Client\Reports\Inspections and it's named healthinspectionreport.rpt, to test your changes, you will need to rename the file to something else. 

Also, sometimes testing your changes requires logging back into the AMO application because sometimes it seems to cache the report, other times you can make changes in Crystal Report Writer and run the report from AMO right away. Not sure if there's a lock or cache thing going on

**Comment by BrendenPautsch-COM** [comment]
I was able to modify the CDC report to combine in the new Guidesheets.  The only issue I see is that the report is much "wider" as there are more columns which makes it not printer friendly.  I was thinking of possibly switching the axis and have the Facility type on the X Axis and the CDC Violation on the Y Axis.  We may need to follow up with Beth about that report in our next status meeting.

**Comment by RikiSjachrani-COM** [comment]
I'm putting in here the other issue Courtney mentions with non-Food and Drink re-inspections. Just want to make sure it gets accounted for in this change

> I did a pool inspection yesterday and AMO is using the logic of “priority” and “additional” violations on the inspection report, but this logic does not apply to licenses outside of food and drink licenses. Any other health license should just have a summary that shows total violations, repeat violations, and if a reinspection is required. Then the violations are just listed out in numerical order, no categorizing like with food and drink. I’ve attached an old pool inspection report so you can see what I mean, and the inspection report from yesterday so you can see the incorrect version of the report.

> Also,  I generated the 2017 report from Accela Web, and it’s randomly putting “NO ESTABLISHMENT” above the license number on the first page. (When generated in AMO the inspection report does not do that.) So when using the web to generate the report, it shouldn’t print that – could you please fix?

- [ ] Fix AMO Inspection Report logic of "Priority" and "Additional" for non-food and drink licenses
- [ ] Fix Accela Web Inspection Report "NO ESTABLISHMENT" above the license number

[sauk creek 2017.pdf](https://github.com/City-of-Madison/Development-Team-2/files/1235420/sauk.creek.2017.pdf)
[sauk creek.pdf](https://github.com/City-of-Madison/Development-Team-2/files/1235419/sauk.creek.pdf)

**Comment by RikiSjachrani-COM** [comment]
Ok, to give an update. Since Test is version 9 of Accela, Courtney will be using the Help Desks loaner surface 4 to test the Guide sheet changes. It looks like Courtney, Stephanie and Beth will be testing this week. 

Has either of you taken a look at scripting changes?

**Comment by JacquelineGoltz-COM** [comment]
I looked at Standard Choice Scripts for Health Food and Drink, I did not see any reference to the inspections.  Brenden did you see anything that I missed?

**Comment by BrendenPautsch-COM** [comment]
- I have updated the InspectionReport in SSRS to account for the No Establishment field in Test (Courtney's Latest Issue).  

- I also just finished up the AMO InspectionReport.  I placed a copy of the local report in my common folder at (F:\Common\Brenden\healthinspectionreport_NEW.rpt) I was not able to attach it to this tread as rpt is not a support file type. I was able to test the reports it against several different License Numbers and Type. (Food & Drink & Swimming Pools).  

- What  is the Test URL for the city of Madison site.  I would like to work on the Public Inspection Report next if possible, just need to figure out where the report is stored (Kim Question?)

**Comment by RikiSjachrani-COM** [comment]
Great, honestly I don't know where to the find the test url. @KimGrittner-COM do you happen to know?

**Comment by PaulOLeary-COM** [comment]
Try http://elamtest.cityofmadison.com/HealthInspections - Web team is doing a "makeover" on it.

**Comment by BrendenPautsch-COM** [comment]
Paul,

That is the page and I was able to find the data source and the stored Procedure that updates the data.  However my current issue lies on that Page.  The data displayed on the elamtest page is live data so I cannot test the test data.  I also think it is using the same criteria that Health Actives uses to determine what priority the violation is, which needs to be updated to account for the the new guidesheets.  Does anyone have an idea how to edit that page?

Thanks in advance,
Brenden

**Comment by PaulOLeary-COM** [comment]
There's a web.config file on the site that I can change to point to the test DB. I'd like to give the web team the heads-up if we're going to do that, just so they know we're moving their cheese.

**Comment by BrendenPautsch-COM** [comment]
Who on the webteam should I contact to edit the actual page (https://elamtest.cityofmadison.com/HealthInspections/Violation.aspx)?

Brenden

**Comment by PaulOLeary-COM** [comment]
@BrendenPautsch-COM , I've made the change to the web.config, and I notified Nathan.

**Comment by JacquelineGoltz-COM** [comment]
I completed QA on the following reports:

•	Health Inspections Report – AMO
•	Health Inspections Report – SSRS 
•	CDC Risk Factor Report (New and Vertical)
•	Health Actives Report – New Field Names
•	Restaurant & Retail Food Store Health Inspection Reports (Web)


•	MadisonAccela Data
o	spRestaurantInspection
o	getInspectionCDCViolations
o	getInspectionViolations
o	HealthActive

**Comment by BrendenPautsch-COM** [comment]
Finished updating the InspectionHealth Report with the updates from Courtney.  

Riki, can you please QA as I believe this is the last report that needs to QA and customer tested. 

I have attached my test print of the reports both the AMO and the SSRS version.  The only noticeable data difference is the inspector information under the signatures. in AMO it uses the person who is logged into the AMO where the SSRS version actually uses who did the report.  999 out of 1000, the person running the AMO report will be the Inspector.  Also the missing data like licensee, contact and Sanitarian are not populated in the AMO version.  The way the report is set up, each section is its own sub report, many with the details hidden only displaying the Report/Group summary.  While testing I showed the detail and the data did not appear on any line.
[HealthInspection QA Reports.pdf](https://github.com/City-of-Madison/Development-Team-2/files/1252266/HealthInspection.QA.Reports.pdf)

**Comment by JacquelineGoltz-COM** [comment]
We had a conference call this morning with Courtney so we could better understand her issue. Brenden is currently making the latest the changes requested by Courtney.  The summary section of the Health Inspection report is not printing correctly on Food and Drink records.   The repeat statement is also printing at times when there is not a repeat violation.

**Comment by JacquelineGoltz-COM** [comment]
@BrendenPautsch-COM Final QA is finished today.  Everything looks good.  I ran swimming pool, hotel and food/drink records.  Created routine inspections no violation, violation with repeat, scheduled reinspections,  violation not corrected, violation corrected and on site.  I am going to email Courtney today.

**Comment by JacquelineGoltz-COM** [comment]
I sent an email to Courtney on 10/9 for final approval. Waiting to hear back.

**Comment by JacquelineGoltz-COM** [comment]
@RikiSjachrani-COM and @BrendenPautsch-COM Courtney Z has approved the project for production.  I will plan to do this on Monday 10/16.

**Comment by JacquelineGoltz-COM** [comment]
Move Guidesheets to Production

- [ ] LIC_FOOD IONN 2017
- [ ] LIC_FOOD IONN OTHER 2017
 - [ ] LIC FOOD GRP 2017
- [ ]  LIC FOOD GRP OTHER 2017

**Comment by JacquelineGoltz-COM** [comment]
AMO changes and reports are in production.  Issues have been brought to our attention. Courtney forgot to tell us that Madison and Dane County Schools food service are included on the Health Inspection report.
We added that portion.  Subsequent reinspections are to also have the summary showing.  The changes are in test.
