### ISSUE TITLE
State Fees Report Issue - Jackie

### ISSUE THREAD

**Issue by JacquelineGoltz-COM** [City-of-Madison/Development-Team-2#61]
Updated query to include the new fees that were increased in April of 2018.  The changes will affect the first and second quarter of 2018.  I am leaving the case statement for the previous fee schedule as well.  I have the changes in test, waiting to hear back fromBill.

**Comment by JacquelineGoltz-COM** [comment]
We can discuss this during meeting on 01/09/2019

**Comment by JacquelineGoltz-COM** [comment]
Ann and Bill will go over the listings I sent them and get back to us.

**Comment by JacquelineGoltz-COM** [comment]
Ann has the test version of the report and will get back to me when she is done testing.

**Comment by RikiSjachrani-COM** [comment]
Talked with Bill and checked in

**Comment by JacquelineGoltz-COM** [comment]
Brenden worked sql code for State Fees  and is now using the Create Date for the parameters. Bill and Ann have approved the changes.

**Comment by JacquelineGoltz-COM** [comment]
Bill Sullivan approved the changes.  They will send an service request in the future for adding in Town of Blooming Grove.
