### ISSUE TITLE
SR-13-0000431 - Reconfigure Accela documents as ADS EDMS not Sharepoint

### ISSUE THREAD

**Issue by KimGrittner-COM** [City-of-Madison/Development-Team-2#8]
This project is being developed on AccelaDev, then AccelaStage for user testing.

TODO for this project

- [x] 1. Create new table BDOC_ADS_SYNC on MadisonAccela to track INSERT and DELETE of Accela.BDOCUMENT rows with a SOURCE_NAME = 'ADS'
- - [x] Prod

- [x] 2. Create stored procedure spUPDATE_BDOCS_ADS_SYNC on MadisonAccela to add rows into BDOC_ADS_SYNC to track new BDOCUMENT documents and update existing rows where a BDOCUMENT file has been deleted.
- - [x] Prod

- [x] 3. Create .NET Executable SYNC_ADS_Sharepoint.exe which will be run as a batch to process documents based on the information in the BDOC_ADS_SYNC table.
- - [x] Prod - Copy from Test
- - [ ] Prod - UPDATE App.config file
- - - [x] Emails
- - - [x] Web Service name
- - - [ ] SharepointDocServer ???
- - - [x] DB Connection string / ADS DB name
- - - [x] ADS Repository Dir name

- [x] 4.  Change default Repository for one module in the dev environment.  And test ACA document uploads.  

- [x] 5.  Test the handling of special characters for filenames, like "&" and ".." .  

- [x] 6. Define which ENT_TYPE BDOCUMENT records we need to push to SharePoint besides "CAP" and "INSPECTIONS"  Result: everything except for TMP_CAP

- [x] 7.  Add to the SELECT criteria that reads BDOCUMENT based on the ENT_TYPEs that should be included.  

- [x] 8.  Test the handling of a file where the file extension does not match the actual file such as a .jpg which was named .pdf.  Works like this, uploads to Accela but tries to open in the expected format, works in SharePoint and opens in the correct format.  Tested by renaming a .pdf as a .jpg.

- [ ] 9.  Accela app-level tasks/issues. (All checkboxes cleared for PROD)
- - [x] Set up ADS EDMS - ***CONTACT NET ADMIN*** re. name/IP
- - [x] Update EDMS Security Policy - Defaults, options to add/delete/etc
- - [x] Form Portlets for Record Document List, Document Form
- - [x] Update Report Manager entries to save to ADS (SQL back-end update)
- - [x] ADS Requires document name, how to resolve.  Riki and Paul

- [x] 10.  Within Accela the download document links work differently.  How to deal with this?  

- [x] 11.  Install the executable and .CMD Batch file.  Set up permissions for this.
- - [x] Dev - \\\elam73dev\Accela\ADSSync
- - [x] Test - \\\ELAMTest\ADSSync
- - [x] Prod - \\\ELAM7Report\ADSSync

- [ ] 12.  Schedule the .CMD batch file to run.
- - [x] Dev - \\\elam73dev\Accela\ADSSync
- - [ ] Test - \\\ELAMTest\ADSSync
- - [ ] Prod - \\\ELAM7Report\ADSSync

- [x] 13. Test on Dev then Promote to Test environment when complete.

- [ ] 14.  Test on Test Environment then Promote to Production when complete.

**Comment by PaulOLeary-COM** [comment]
DEV Repository parent folder is: \\elamdevapp\accela\FileDB\ADS001

**Comment by PaulOLeary-COM** [comment]
If you want to programmatically determine the repository location - albeit relative to the server:

SELECT [PROFILE_VALUE]
  FROM [AccelaADSDev].[dbo].[RDOC_CONFIG_PROV_PROFILE]
  where SERV_PROV_CODE = 'ads001'
  and profile_name = 'FileRepository-FileDatabase'

**Comment by KimGrittner-COM** [comment]
Paul, what user has rights to connect \elamdevapp\accela\FileDB\ADS001
Tried my login and elamdev 
both failed

**Comment by KimGrittner-COM** [comment]
In the BDOCUMENT table on production there are 6 different ENT_TYPEs.
**Which ones do we want in SharePoint?**
**CAP and INSPECTION I am sure about, but what about TMP_CAP, PARCEL and the rest?**

Thanks

select distinct count(*) as cnt, ent_type from bdocument group by ent_type order by ent_type

Here are the stats from 9/8/2017 
===========================
count	ent_type
=====   ================
799747    CAP
28723	INSPECTION
23140	TMP_CAP
42	         PARCEL
10	         ASSET
1	         SET

**Comment by PaulOLeary-COM** [comment]
So ADS Test is running. TEST Repository parent folder is: \\\elam73testapp\accela\FileDB\ADS001 
@KimGrittner-COM - see if you can browse to that folder.

**Comment by PaulOLeary-COM** [comment]
Okay, I've made ADS the default EDMS for Permitting. I've also made it the default for PermittingPublicUser group (ACA Permits), with delete disabled.

**Comment by KimGrittner-COM** [comment]
PaulOLeary-COM Yes I can get to that folder.  Thanks
